---
- hosts: stopbe
  gather_facts: true
  roles:
    - STOPBE
  vars_files:
    - "vars/main.yml"

- hosts: cmedb
  gather_facts: true
  roles:
    - CMEDB
  vars_files:
    - "vars/main.yml"

- hosts: mongo
  gather_facts: false
  roles:
    - MONGO
  vars_files:
    - "vars/main.yml"

- hosts: loaniqdb
  gather_facts: false
  roles:
    - LOANIQDB
  vars_files:
    - "vars/main.yml"

- hosts: restapi
  gather_facts: false
  roles:
    - RESTAPI
  vars_files:
    - "vars/main.yml"

- hosts: misysboard
  gather_facts: true
  roles:
    - MISYSBRD
  vars_files:
    - "vars/main.yml"

- hosts: startbe
  gather_facts: true
  roles:
    - STARTBE
  vars_files:
    - "vars/main.yml"
