---
- name: Start all services on cmedb
  hosts: cmedb
  gather_facts: false
  vars_files:
    - "vars/main.yml"

  tasks:
   - name: Start FBLCME-MongoDB service
     win_service:
       name: FBLCME-MongoDB
       state: started
       start_mode: delayed
       username: LocalSystem

   - name: Start FBLCME-Tomcat8.5 service
     win_service:
       name: FBLCME-Tomcat8.5
       state: started
       start_mode: delayed
       username: LocalSystem

   - name: Start FBLCME-Tomcat8.5-Scheduler-DDT service
     win_service:
       name: FBLCME-Tomcat8.5-Scheduler-DDT
       state: started
       start_mode: delayed
       username: LocalSystem

   - name: Start FBLCME-Tomcat8.5-Scheduler-HDE service
     win_service:
       name: FBLCME-Tomcat8.5-Scheduler-HDE
       state: started
       start_mode: delayed
       username: LocalSystem

- name: Start service on loaniqdb
  hosts: loaniqdb
  gather_facts: false
  vars_files:
    - "vars/main.yml"

  tasks:
   - name: Start Loaniq service
     win_service:
       name: STARTLIQ_2020
       state: started
       start_mode: delayed
       username: LocalSystem

- name: Start service on restapi
  hosts: restapi
  gather_facts: false
  vars_files:
    - "vars/main.yml"

  tasks:
   - name: Start Loaniq service
     win_service:
       name: STARTLIQ_2020
       state: started
       start_mode: delayed
       username: LocalSystem

- name: Start service on misysboard
  hosts: misysboard
  gather_facts: false
  vars_files:
    - "vars/main.yml"

  tasks:
   - name: Start Loaniq service
     win_service:
       name: FBL_Misysboard
       state: started
       start_mode: delayed
       username: LocalSystem
