---
- hosts: source
  gather_facts: false
  
  vars_files:
    - "vars/main.yml"


  tasks:
  - name: Stop a service
    win_service:
      name: TapiSrv
      state: stopped

   
  - name: Create directory Release
    win_file:
      path: C:\Release\FBL_2.2.20
      state: directory


  - name: Create directory LOANIQ
    win_file:
      path: C:\LOANIQ\Server
      state: directory


  - name: Copy LOANIQ to Release
    become_method: runas
    win_shell: copy-item \\10.10.12.151\loaniq\Server  -destination C:\Release\FBL_2.2.20 -recurse
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt
   

  - name: Copy LOANIQ to target
    become_method: runas
    win_shell: copy-item \\10.10.12.151\loaniq\Server\misysboard_node  -destination C:\LOANIQ\Server -recurse
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt


  - name: Change Hostname in mb-package.json
    become_method: runas
    win_shell: ((get-content -path C:\loaniq\Server\misysboard_node\mb-package.json -Raw) -replace 'FBLQARAPI','ENKEFBLDEVAPI') | set-content -path  C:\loaniq\Server\misysboard_node\mb-package.json
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt


  - name: Change Hostname in config.json
    become_method: runas
    win_shell: |
      $json = Get-Content 'C:\loaniq\Server\misysboard_node\addons\fbl_common\config\generated\config.json' -raw | ConvertFrom-Json
      $json.connection | % {if($_.serverName -eq 'FBLQAUXP.develop.fcbt'){$_.serverName='ENKEFBLDEVUXP.develop.fcbt'}}
      $json | ConvertTo-Json -depth 32| set-content 'C:\loaniq\Server\misysboard_node\addons\fbl_common\config\generated\config.json'
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt

  
  - name: Remove subfolders
    become_method: runas
    win_shell: Get-ChildItem -Path C:\loaniq\Server\misysboard_node\data\Users -Recurse| Foreach-object {Remove-item -Recurse -path $_.FullName }
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt

  

  - name: Share and set permissions C:\LOANIQ
    become_method: runas
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt
    win_share:
      name: LOANIQ
      path: C:\LOANIQ
      full: Administrators
      read: Everyone


  - name: Set C:\LOANIQ  folder permissions
    become_method: runas
    become: yes
    become_user: svcEnkeDeployments@develop.fcbt
    win_acl:
      path: C:\LOANIQ
      user: Everyone
      rights: ReadAndExecute, ListDirectory
      type: allow
      propagation: 'None'

  - name: Set C:\LOANIQ folder permissions
    become_method: runas
    become: yes
    become_user: iyakubenko0519@nterprise.net
    win_acl:
      path: C:\LOANIQ
      user: DBA_Admins@nterprise.net
      rights: FullControl
      type: allow
    vars:
      ansible_become_password: L3tsdanc311!!Ok3

  - name: Start a service
    win_service:
      name: TapiSrv
      state: started

