- name: Copy script file to DB host
  win_copy:
    src: "{{ Scriptsource }}/script.js"
    dest: "{{ MongoFolder }}\\script.js"

- name: Change host url
  become_method: runas
  become: true
  win_shell: mongo "{{ Scriptpath }}" script.js
  args:
    executable: cmd
    chdir: "{{ MongoFolder }}"
