# Connection
ansible_winrm_transport: ntlm
ansible_user:  develop\svcEnkeDeployments
ansible_password: FarmCreditBank#1
ansible_become_password: "{{ ansible_password }}"
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
ansible_winrm_send_cbt: false

ansible_become_user: "{{ ansible_user }}"
ansible_become_pass: "{{ ansible_password }}"

ServiceNane: startliq_2020

LatestRelese: '2.2.11'
SharePath: '\\FBLQARAPI\C$\LOANIQ'
MainSourceServer: FBLQARAPI
MainTargetServer: ENKEFBLDEVRAPI
SourceBEhost: 'FBLQABE'
TargetBEhost: 'ENKEFBLDEVBE'
SourceMThost: FBLQAMT
TargetMThost: ENKEFBLDEVMT
SourceFBLhost: FBLQACME
TargetFBLhost: ENKEFBLDEVCMEFE
LIQPASSWORD: LIQPASSWORD

