- name: Stop FBLCME-MongoDB service
  win_service:
    name: FBLCME-MongoDB
    state: stopped
    start_mode: manual
    username: LocalSystem

- name: Stop FBLCME-Tomcat8.5 service
  win_service:
    name: FBLCME-Tomcat8.5
    state: stopped
    start_mode: manual
    username: LocalSystem

- name: Stop FBLCME-Tomcat8.5-Scheduler-DDT service
  win_service:
    name: FBLCME-Tomcat8.5-Scheduler-DDT
    state: stopped
    start_mode: manual
    username: LocalSystem

- name: Stop FBLCME-Tomcat8.5-Scheduler-HDE service
  win_service:
    name: FBLCME-Tomcat8.5-Scheduler-HDE
    state: stopped
    start_mode: manual
    username: LocalSystem

- name: 'Check that the FBLCME folder exists'
  win_stat:
    path: "{{ cme_fblcme_folder }}"
  register: stat_file

- name: 'Ensure Release folder exist'
  win_file:
    path: 'C:\Releases'
    state: directory
  when: stat_file.stat.exists == True

- name: 'Ensure FBL folder exist'
  win_file:
    path: "C:\\Releases\\FBL_{{ latest_relese }}"
    state: directory
  when: stat_file.stat.exists == True

- name: 'Quick Backup to Release folder'
  win_shell: "mv {{ cme_fblcme_folder }} C:\\Releases\\FBL_{{ latest_relese }}_{{lookup('pipe', 'date +%m_%d_%Y_%H-%M-%S')}}"
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  when: stat_file.stat.exists == True

- name: Copy FBLCME to target
  become_method: runas
  win_shell: copy-item "{{cme_source_app_folder}}" -destination "{{cme_target_app_folder}}" -recurse -ErrorAction SilentlyContinue
  become: yes
  ignore_errors: true

- name: Copy inetpub to target
  become_method: runas
  win_shell: copy-item "{{cme_source_web_folder}}" -destination "{{cme_target_web_folder}}" -recurse -ErrorAction SilentlyContinue
  become: yes
  ignore_errors: true

- name: Change Hostname in C:\FBLCME\Tomcat8.5\server.xml file
  become_method: runas
  win_shell: ((get-content -path "{{ cme_tomcat_folder }}\\conf\\server.xml" -Raw) -replace 'fblcme-qa','enkefbldevcmefe') | set-content -path  "{{ cme_tomcat_folder }}\\conf\\server.xml"
  become: yes

- name: Change Hostname in C:\FBLCME\Tomcat8.5\web.xml file
  become_method: runas
  win_shell: ((get-content -path "{{ cme_tomcat_folder }}\\conf\\web.xml" -Raw) -replace 'fblcme-qa','enkefbldevcmefe') | set-content -path  "{{ cme_tomcat_folder }}\\conf\\web.xml"
  become: yes

- name: Remove C:\FBLCME\Tomcat8.5\conf\logs folder
  win_file:
    path: "{{ cme_tomcat_folder }}\\conf\\logs"
    state: absent

- name: Remove C:\FBLCME\Tomcat8.5\conf\temp folder
  win_file:
    path: "{{ cme_tomcat_folder }}\\conf\\temp"
    state: absent

- name: Remove C:\FBLCME\Tomcat8.5\conf\Webapps folder
  win_file:
    path: "{{ cme_tomcat_folder }}\\conf\\Webapps"
    state: absent

- name: Remove C:\FBLCME\Tomcat8.5-Scheduler-DDT\conf\logs folder
  win_file:
    path: "{{ cme_tomcat_folder }}-Scheduler-DDT\\conf\\logs"
    state: absent

- name: Remove C:\FBLCME\Tomcat8.5-Scheduler-HDE\conf\logs folder
  win_file:
    path: "{{ cme_tomcat_folder }}-Scheduler-HDE\\conf\\logs"
    state: absent

- name: Create C:\FBLCME share and set permissions
  become_method: runas
  become: yes
  win_share:
    name: FBLCME
    path: "{{ FBLCME }}"
    full: Administrators
    read: Everyone

- name: Create C:\FBLCME\Tomcat8.5 share and set permissions
  become_method: runas
  become: yes
  win_share:
    name: FBLCME Tomcat
    path: "{{ cme_tomcat_folder }}"
    full: Administrators
    read: Everyone

- name: Set C:\FBLCME folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: "{{ cme_fblcme_folder }}"
    user: Everyone
    rights: ReadAndExecute, ListDirectory
    type: allow
    propagation: 'None'

- name: Set C:\FBLCME\Tomcat8.5 folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: "{{ cme_tomcat_folder }}"
    user: Everyone
    rights: ReadAndExecute, ListDirectory
    type: allow

- name: Set C:\FBLCME folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: "{{ cme_fblcme_folder }}"
    user: DBA_Admins@nterprise.net
    rights: FullControl
    type: allow
  vars:
    ansible_become_user: "{{ cme_admin_user }}"
    ansible_become_password: "{{ cme_admin_password }}"

- name: Set C:\FBLCME\Tomcat8.5 folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: "{{ cme_tomcat_folder }}"
    user: DBA_Admins@nterprise.net
    rights: FullControl
    type: allow
  vars:
    ansible_become_user: "{{ cme_admin_user }}"
    ansible_become_password: "{{ cme_admin_password }}"

- name: Create FBCME database backup
  become_method: runas
  become: true
  win_shell:
    Invoke-Command -ComputerName "{{ mssql_db_instance }}" -ScriptBlock {Backup-SqlDatabase -ServerInstance "{{ mssql_db_instance }}" -Database "{{ cme_db_catalog }}" -BackupFile "{{ db_backup_path }}\\FBCME_preUG_${{lookup('pipe', 'date +%m_%d_%Y_%H%M%S')}}.bak"}

- name: Start FBLCME-MongoDB service
  win_service:
    name: FBLCME-MongoDB
    state: started
    start_mode: delayed
    username: LocalSystem

- name: Start FBLCME-Tomcat8.5 service
  win_service:
    name: FBLCME-Tomcat8.5
    state: started
    start_mode: delayed
    username: LocalSystem

- name: Start FBLCME-Tomcat8.5-Scheduler-DDT service
  win_service:
    name: FBLCME-Tomcat8.5-Scheduler-DDT
    state: started
    start_mode: delayed
    username: LocalSystem

- name: Start FBLCME-Tomcat8.5-Scheduler-HDE service
  win_service:
    name: FBLCME-Tomcat8.5-Scheduler-HDE
    state: started
    start_mode: delayed
    username: LocalSystem
