- name: Check that loaniq service started
  become_method: runas
  become: yes
  win_service:
    name: "{{ loaniq_service_name }}"
    state: stopped 

- name: 'Check that the LOANIQ folder exists'
  win_stat:
    path: 'C:\LOANIQ'
    register: stat_file

- name: 'Ensure Release folder exist'
  win_file:
    path: 'C:\Releases'
    state: directory
    when: stat_file.stat.exists == True

- name: 'Ensure FBL folder exist'
  win_file:
    path: "C:\\Releases\\FBL_{{ LatestRelese }}"
    state: directory
    when: stat_file.stat.exists == True

- name: 'Quick Backup to Release folder'
  win_shell: "mv C:\\LOANIQ C:\\Releases\\FBL_{{ LatestRelese }}"
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only

- name: Copy FBLMT to target
  become_method: runas
  win_shell: copy-item "{{source_mt_app_folder}}" -destination "{{target_mt_app_folder}}" -recurse
  become: yes

- name: Change Hostname in server l2sapp.ini file
  become_method: runas
  win_shell: ((get-content -path C:\LOANIQ\SERVER\L2SAPP.ini -Raw) -replace 'fblqamt','enkefbldevmt') | set-content -path  C:\LOANIQ\SERVER\L2SAPP.ini
  become: yes

- name: rename in LIQSETENV_FBLQAMT.cmd file
  become_method: runas
  win_shell: "cmd.exe /c rename C:\\LOANIQ\\SERVER\\LIQSETENV_FBLQAMT.cmd LIQSETENV_ENKEFBLDEVMT.cmd"
  become: yes

- name: Change Hostname in context.xml
  become_method: runas
  win_shell: ((get-content -path C:\LOANIQ\SERVER\Tomcat\conf\context.xml -Raw) -replace 'fblqamt','enkefbldevmt') | set-content -path  C:\LOANIQ\SERVER\Tomcat\conf\context.xml
  become: yes

- name: Change Hostname in jsqlaccessproperties.xml
  become_method: runas
  win_shell: ((get-content -path C:\LOANIQ\SERVER\Tomcat\jrconf\jsqlaccessproperties.xml -Raw) -replace 'fblqamt','enkefbldevmt') | set-content -path  C:\LOANIQ\SERVER\Tomcat\jrconf\jsqlaccessproperties.xml
  become: yes

- name: Remove Tomcats logs
  become_method: runas
  win_shell: "cmd.exe /c del C:\\LOANIQ\\SERVER\\Tomcat\\logs\\* /s /q"
  become: yes

- name: Remove Tomcats temp folder content
  become_method: runas
  win_shell: "cmd.exe /c del C:\\LOANIQ\\SERVER\\Tomcat\\temp\\* /s /q"
  become: yes

- name: Remove Tomcats Jackrabbit folder
  become_method: runas
  win_shell: "cmd.exe /c rmdir C:\\LOANIQ\\SERVER\\Tomcat\\webapps\\Jackrabbit /s /q"
  become: yes

- name: Remove Tomcats liq_APIWebService folder
  become_method: runas
  win_shell: "cmd.exe /c rmdir C:\\LOANIQ\\SERVER\\Tomcat\\webapps\\liq_APIWebService /s /q"
  become: yes

- name: Remove Tomcats liq_LinkageMap folder
  become_method: runas
  win_shell: "cmd.exe /c rmdir C:\\LOANIQ\\SERVER\\Tomcat\\webapps\\liq_LinkageMap /s /q"
  become: yes

- name: Change Hostname in client l2sapp.ini file
  become_method: runas
  win_shell: ((get-content -path C:\LOANIQ\CLIENT\L2SAPP.ini -Raw) -replace 'fblqamt','enkefbldevmt') | set-content -path  C:\LOANIQ\CLIENT\L2SAPP.ini
  become: yes

- name: 'Encrypt the LS2APP.ini password'
  win_shell: "LS2UTIL -util ENCR_PASS -pwd {{ LIQPASSWORD }} -ini LS2APP.INI > pwd.out"
  args:
    chdir: C:\LOANIQ\SERVER\
    executable: cmd

- name: 'Encrypt password'
  win_shell: "SCRIPT.CMD"
  args:
    chdir: C:\LOANIQ\SERVER\
    executable: cmd
    stdin: "{{ LIQPASSWORD }}"
  register: EncrypredPassword

- set_fact: pwd="{{ EncrypredPassword.stdout | trim }}"

- debug:
    msg: "{{ pwd }}"

- name: 'Replace string'
  win_lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.sourceline }}"
    line: "{{ item.targetline }}"
  with_items:
     - { path: "C:\\LOANIQ\\SERVER\\Tomcat\\conf\\context.xml", sourceline: "password=*.*", targetline: 'password="{{ pwd }}"'}
     - { path: "C:\\LOANIQ\\SERVER\\Tomcat\\jrconf\\jsqlaccessproperties.xml", sourceline: '<entry key="DBDefaultPassword*', targetline: '<entry key="DBDafaultPassword">{{ pwd }}</entry>' }

- name: Create C:\LOANIQ\CLIENT share and set permissions
  become_method: runas
  become: yes
  win_share:
    name: CLIENT
    path: C:\LOANIQ\CLIENT
    full: Administrators
    read: Everyone

- name: Set C:\LOANIQ\CLIENT folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\CLIENT
    user: Everyone
    rights: ReadAndExecute, ListDirectory
    type: allow
    propagation: 'None'

- name: Set C:\LOANIQ\CLIENT folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\CLIENT
    user: DBA_Admins@nterprise.net
    rights: FullControl
    type: allow

- name: Set C:\LOANIQ\CLIENT folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\CLIENT
    user: Administrators
    rights: FullControl
    type: allow

- name: Create C:\LOANIQ\SERVER share and set permissions
  become_method: runas
  become: yes
  win_share:
    name: SERVER
    path: C:\LOANIQ\SERVER
    full: Administrators
    read: Everyone

- name: Set C:\LOANIQ\SERVER folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\SERVER
    user: Everyone
    rights: ReadAndExecute, ListDirectory
    type: allow
    propagation: 'None'

- name: Set C:\LOANIQ\SERVER folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\SERVER
    user: DBA_Admins@nterprise.net
    rights: FullControl
    type: allow

- name: Set C:\LOANIQ\SERVER folder permissions
  become_method: runas
  become: yes
  win_acl:
    path: C:\LOANIQ\SERVER
    user: Administrators
    rights: FullControl
    type: allow

- name: ms sql fbloaniq backup
  become_method: runas
  become: yes
  win_shell: Invoke-Command -ComputerName {{InstanceMSSQL}} -ScriptBlock {Backup-SqlDatabase -ServerInstance "{{InstanceMSSQL}}" -Database "{{loaniq_db_catalog}}" -BackupFile "{{BackupPath}}\\FBLOANIQ_preUG{{lookup('pipe', 'date +%m_%d_%Y_%H%M%S')}}.bak"}

- name: Check that loaniq service started
  become_method: runas
  become: yes
  win_service:
    name: "{{ loaniq_service_name }}"
    state: started 
